name: ai_crypto_alert
description: AI Crypto Price Alert
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  cupertino_icons: ^1.0.8
  equatable: ^2.0.7
  flutter_svg: ^2.0.10+1
  go_router: ^14.6.1
  rxdart: ^0.28.0
  shared_preferences: ^2.3.2
  # the annotation package containing @riverpod
  riverpod_annotation: ^2.6.1
  dio: ^5.7.0
  pretty_dio_logger: ^1.4.0
  lottie: ^3.1.3
  #  connectivity_plus: 6.1.0
  flutter_platform_widgets: ^7.0.1
  flutter_hooks: ^0.20.5
  google_fonts: ^6.2.1
  hooks_riverpod: ^2.6.1
  json_annotation: ^4.9.0
  cached_network_image: ^3.4.1
  flutter_riverpod: ^2.6.1
  font_awesome_flutter: ^10.8.0
  smooth_sheets: ^0.10.2
  moon_design: ^1.0.7
  google_sign_in: ^6.2.2
  sign_in_with_apple: ^6.1.3
  flutter_dotenv: ^5.2.1
  in_app_purchase: ^3.2.0
  freezed_annotation: ^2.4.4
  shimmer: ^3.0.0
  icons_plus: ^5.0.0
  flutter_animate: ^4.5.2
  in_app_purchase_platform_interface: ^1.4.0
  provider: ^6.1.2
  sqflite: ^2.4.1
  logger: ^2.5.0
  easy_refresh: ^3.4.0
  url_launcher: ^6.3.1
  crypto: ^3.0.6
  image_picker: ^1.1.2
  extended_nested_scroll_view: ^6.2.1
  loading_more_list: ^7.1.0
  easy_sticky_header: ^1.1.1
  sliver_tools: ^0.2.12
  flutter_native_splash: ^2.4.3
  animated_text_kit: ^4.2.2
  gradient_borders: ^1.0.1
  share_plus: ^10.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0
  json_serializable: ^6.9.0
  freezed: ^2.5.7
  build_runner: ^2.4.13
  flutter_gen_runner:
  riverpod_generator: ^2.6.3
  riverpod_lint: ^2.6.3
  custom_lint: ^0.7.0

flutter_gen:
  output: lib/gen/ # Optional (default: lib/gen/)
  fonts:
    enabled: true
  integrations:
    flutter_svg: true

import_sorter:
  comments: false # Optional, defaults to true
  ignored_files: # Optional, defaults to []
    - \/lib\/*

flutter_native_splash:
  # This package generates native code to customize Flutter's default white native splash screen
  # with background color and splash image.
  # Customize the parameters below, and run the following command in the terminal:
  # flutter pub run flutter_native_splash:create
  # To restore Flutter's default white splash screen, run the following command in the terminal:
  # flutter pub run flutter_native_splash:remove
  background_image: "assets/splash/splash_bg.png"
  android: true
  ios: true
  fullscreen: true
  android_gravity: center
  ios_content_mode: center


flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/envs/
    - assets/envs/.env
    - assets/envs/.env.staging
    - assets/icons/
    - assets/images/
    - assets/videos/
    - assets/lotties/
    - assets/

